### ISSUE TITLE
"Pay for order" page looks bad

### ISSUE THREAD

**Issue by claudiosmweb** [woothemes/storefront#150]
![screenshot from 2015-03-29 19 02 43](https://cloud.githubusercontent.com/assets/1264099/6888001/5ac02346-d646-11e4-8c94-78dbc784da19.png)

**Comment by jameskoster** [comment]
@claudiosmweb latest Storefront? I'm sure I fixed this. https://github.com/woothemes/storefront/issues/137

**Comment by jameskoster** [comment]
ok ignore that, I see the issue.

**Comment by simonjson** [comment]
Hi,
I use Storefront version 1.4.6 - but still got the "Pay for Order" problem. I don't know how to solve this - please help!
Simon

**Comment by mikeyarce** [comment]
Can confirm this is still happening in Storefront 1.4.6
Example:
![screen shot 2015-07-30 at 10 51 43 am](https://cloud.githubusercontent.com/assets/3220162/8990735/0aa7a23a-36a9-11e5-9bca-f8fc7af5cdd0.png)
cc @jameskoster

**Comment by claudiosmweb** [comment]
Yeah, Tested and still looks bad =/

**Comment by jameskoster** [comment]
@claudiosmweb @mikeyarce would you mind checking with latest dev version?

**Comment by mikeyarce** [comment]
@jameskoster looking at the latest Storefront master from Github, I still get the same issue.
The issue is coming from this line:
https://github.com/woothemes/storefront/blob/master/inc/woocommerce/css/woocommerce.scss#L1829-L1830
Since these parent classes `.woocommerce-order-pay,.page-template-template-fullwidth-php.woocommerce-order-pay` don't exist on that page, the CSS isn't loading there.

Looking at that page, maybe adding `.woocommerce` or `.woocommerce-checkout` to those parent classes will fix the issue, but I'm not sure what the best practice would be without breaking other page layouts.

**Comment by jameskoster** [comment]
Thanks @mikeyarce 

Hmm. `.woocommerce-order-pay` should be there. How are you getting to that page? When I create an unpaid order on the backend then go to pay it on the frontend it works fine. You guys are obviously doing something different though xD

**Comment by mikeyarce** [comment]
WooCommerce 2.4 adds the `.woocommerce-order-pay` class back to that page, but 2.3.13 did not have that body class.

**Comment by jameskoster** [comment]
Ah ok, so this will resolve itself when 2.4 goes live.
